//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public string MRDno { get; set; }
        public string Term { get; set; }
        public string GestationalAge { get; set; }
        public string AgaSgaLga { get; set; }
        public string LbwVlbwElbw { get; set; }
        public string Morbidity { get; set; }
        public string MorbiditiesTreatment { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
