//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDI_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nicuEntities : DbContext
    {
        public nicuEntities()
            : base("name=nicuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Anticonvulsant> Anticonvulsants { get; set; }
        public virtual DbSet<Diagnosi> Diagnosis { get; set; }
        public virtual DbSet<Immunization> Immunizations { get; set; }
        public virtual DbSet<Investigation> Investigations { get; set; }
        public virtual DbSet<PatientRisk> PatientRisks { get; set; }
        public virtual DbSet<Morbidity> Morbidities { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<MedicationType> MedicationTypes { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
    }
}
