//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Diagnosis = new HashSet<Diagnosi>();
        }
    
        public string MRDno { get; set; }
        public string NDno { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string PhoneNo { get; set; }
        public string GestationalAge { get; set; }
        public int BirthWeight { get; set; }
        public int WeightOnDischarge { get; set; }
        public int HCOnDischarge { get; set; }
        public int LengthOnDischarge { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string CurrentAge { get; set; }
        public System.DateTime DateOfAdmission { get; set; }
        public System.DateTime Edd { get; set; }
        public string CurrentGestationalAge { get; set; }
        public System.DateTime DateOfDischarge { get; set; }
        public string Adress { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Medication { get; set; }
        public string Anticonvulsant1 { get; set; }
        public string Term { get; set; }
        public string AgaSgaLga { get; set; }
        public string LbwVlbwElbw { get; set; }
        public string Morbidity { get; set; }
        public string MorbiditiesTreatment { get; set; }
        public string InvestigationType { get; set; }
        public string Severity { get; set; }
        public string Reason { get; set; }
        public string ImmunnizationType { get; set; }
        public string Risks { get; set; }
    
        public virtual Anticonvulsant Anticonvulsant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnosi> Diagnosis { get; set; }
        public virtual Immunization Immunization { get; set; }
        public virtual Investigation Investigation { get; set; }
        public virtual PatientRisk PatientRisk { get; set; }
        public virtual Medication Medication1 { get; set; }
    }
}
