//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRisk
    {
        public string MRDno { get; set; }
        public string Risks { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<int> OverallSeverity { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
